// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AsyncVideoController from "./async_video_controller.js"
application.register("async-video", AsyncVideoController)

import CheckoutController from "./checkout_controller.js"
application.register("checkout", CheckoutController)

import ColorPickerController from "./color_picker_controller.js"
application.register("color-picker", ColorPickerController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import MerchantEditController from "./merchant_edit_controller.js"
application.register("merchant-edit", MerchantEditController)

import MerchantNameController from "./merchant_name_controller.js"
application.register("merchant-name", MerchantNameController)

import MerchantStatsController from "./merchant_stats_controller.js"
application.register("merchant-stats", MerchantStatsController)

import NavbarController from "./navbar_controller.js"
application.register("navbar", NavbarController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import NumericInputController from "./numeric_input_controller.js"
application.register("numeric-input", NumericInputController)

import SortableController from "./sortable_controller.js"
application.register("sortable", SortableController)
