// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AsyncVideoController from "./async_video_controller.js"
application.register("async-video", AsyncVideoController)

import CheckoutController from "./checkout_controller.js"
application.register("checkout", CheckoutController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import EditMerchantController from "./edit_merchant_controller.js"
application.register("edit-merchant", EditMerchantController)

import MerchantNameController from "./merchant_name_controller.js"
application.register("merchant-name", MerchantNameController)

import MerchantStatsController from "./merchant_stats_controller.js"
application.register("merchant-stats", MerchantStatsController)

import NumericInputController from "./numeric_input_controller.js"
application.register("numeric-input", NumericInputController)

import SortableController from "./sortable_controller.js"
application.register("sortable", SortableController)
