inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

Metrics/AbcSize:
  Max: 17

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 8

Layout/LineLength:
  Max: 198

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - config/routes.rb
    - config/environments/*

Style/AsciiComments:
  Exclude:
    - config/initializers/money.rb
