inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 17

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 8

Layout/LineLength:
  Max: 198
