inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Max: 17

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 8

Layout/LineLength:
  Max: 198

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/schema.rb

Style/NumericLiterals:
  Exclude: 
    - db/schema.rb