AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
  - config/routes.rb
  - config/environments/*

Layout/LineLength:
  Max: 198

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Style/AsciiComments:
  Exclude:
    - config/initializers/money.rb
